name: Docker Image CI

on:
  push:
    branches:
      - main

permissions:
  contents: read  # 如果需要推送镜像到 registry，需提升权限（如 write）
  #（如果需要推送，可改为：permissions: contents: read, write）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU and Buildx
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub (可选，如果需要推送)
      if: startsWith(github.event.push.branch, 'main')
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.arm64v8
        platforms: linux/arm64/v8
        tags: wekan:${{ github.run_id }}  # 使用 GitHub 环境变量
        #（如果需要推送，添加：push: true）

    - name: Output image digest
      env:
        DIGEST: ${{ steps.docker_build.outputs.digest }}
      run: echo "Image digest: $DIGEST"
